---
version: "2.0"
services:
  web:
    image: itzg/minecraft-server
    expose:
      - port: 25565
        as: 25565
        to:
          - global: true
    env:
      - EULA=TRUE
      - SERVER_NAME=AkashElizaMinecraft
      - MEMORY=4G
      - MAX_PLAYERS=10
    params:
      storage:
        data:
          mount: /data
          readOnly: false

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 2
        memory:
          size: 5Gi
        storage:
          - size: 5Gi
          - name: data
            size: 5Gi
            attributes:
              persistent: true
              class: beta3
  placement:
    akash:
      pricing:
        web:
          denom: uakt
          amount: 10000
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
      attributes:
        host: akash
deployment:
  web:
    akash:
      profile: web
      count: 1